---
apiVersion: v1
kind: Namespace
metadata:
  name: efk
---
apiVersion: v1
kind: Service
metadata:
  name: es-headless
  labels:
    app: es-sts
  namespace: efk
spec:
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: cluster
  clusterIP: None
  selector:
    app: es-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: efk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es-sts
  serviceName: es-headless
  template:
    metadata:
      name: elasticsearch
      labels:
        app: es-sts
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          ports:
          - containerPort: 9200
            name: web
          - containerPort: 9300
            name: cluster
          volumeMounts:
          - name: data
            mountPath: /home/app/data
          env:
            - name: cluster.name
              value: LogsDashboard
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.ping.unicast.hosts
              value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
            - name: discovery.zen.minimum_master_nodes
              value: "2"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/app/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /home/app/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hostpath
      resources:
        requests:
          storage: 100Gi
