---
apiVersion: v1
kind: Namespace
metadata:
  name: efk
---
apiVersion: v1
kind: Service
metadata:
  name: es-headless
  labels:
    app: es-sts
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.elasticSearch.port }}
    name: rest
  - port: {{ .Values.elasticSearch.clusterPort }}
    name: cluster
  clusterIP: None
  selector:
    app: es-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.elasticSearch.replicas }}
  selector:
    matchLabels:
      app: es-sts
  serviceName: es-headless
  template:
    metadata:
      name: elasticsearch
      labels:
        app: es-sts
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          ports:
          - containerPort: {{ .Values.elasticSearch.port }}
            name: web
          - containerPort: {{ .Values.elasticSearch.clusterPort }}
            name: cluster
          volumeMounts:
          - name: data
            mountPath: {{ .Values.elasticSearch.data }}
          env:
            - name: cluster.name
              value: {{ .Values.elasticSearch.clusterName }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.zen.ping.unicast.hosts
              value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
            - name: discovery.zen.minimum_master_nodes
              value: {{ .Values.elasticSearch.minimum_master_nodes }}
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            limits:
              cpu: {{ .Values.elasticSearch.cpu_limit }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 {{ .Values.elasticSearch.data }}"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: {{ .Values.elasticSearch.data }}
      - name: init-sysctl
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count={{ .Values.elasticSearch.max_map_count }}"]
        securityContext:
          privileged: true
      - name: increase-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n {{ .Values.elasticSearch.ulimit}}"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hostpath
      resources:
        requests:
          storage: {{ .Values.elasticSearch.storage }}
