---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  labels:
    app: fluentd
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        volumeMounts:
          - name: log
            mountPath: {{ .Values.fluentd.log }}
          - name: containerlog
            mountPath: {{ .Values.fluentd.containerlog }}
            readOnly: true
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.efk.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: {{ .Values.elasticSearch.port }}
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENT_UID
            value: "0"
        resources:
          limits:
            memory: {{ .Values.fluentd.cpu_limit }}
          requests:
            cpu: 100m
            memory: {{ .Values.fluentd.cpu_request }}
      volumes:
        - name: log
          hostPath:
            path: {{ .Values.fluentd.log }}
        - name: containerlog
          hostPath:
            path: {{ .Values.fluentd.containerlog }}
      serviceAccount: fluentd
      serviceAccountName: fluentd
